### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by volisoft** [WantedTechnologies/xpresso#1]
Hi there,

The library looks awesome, however have some troubles trying to use it.
Because I didn't find the library artifacts deployed to maven central repository I decided to build it by myself.

Build platform details: 
OS: Windows 7, x64
JDK: 1.8.0_40
maven version: 3.3.3

Command I use to build: mvn clean package -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8 -Dproject.build.sourceEncoding=UTF-8

This gives me a bunch of errors like below:

>[ERROR] COMPILATION ERROR :
>[INFO] -------------------------------------------------------------
>[ERROR] >/C:/workspaces/xpresso/src/main/java/com/wantedtech/common/xpresso/helpers/XUtils.java:[517,28] method sort in class java.util.Collections cannot be applied to given types;
>  required: java.util.List<T>
> found: java.util.ArrayList<KeyValue<?,T>>
> reason: explicit type argument KeyValue<?,T> does not conform to declared bound(s) java.lang.Comparable<? super KeyValue<?,T>>

Is there any build instructions?

Cheers

**Comment by aburkov** [comment]
Hi, we'll investigate that. You could still use the latest compiled jar, you can find it here https://github.com/WantedTechnologies/xpresso/tree/master/target

**Comment by aburkov** [comment]
We have been able to reproduce your error message and after a fix the project builds with command:

> mvn compile

Please try again.

**Comment by volisoft** [comment]
Thank you for prompt response.

There is only single compilation error left (see below).
I renamed CSV.java to csv.java and build completed successfully.

Many thanks!

>[ERROR] COMPILATION ERROR :
>[INFO] -------------------------------------------------------------
>[ERROR] >/C:/voli/workspaces/idea/xpresso/src/main/java/com/wantedtech/common/xpresso/csv/CSV.java:>[14,8] class csv is public, should be declared in a file named csv.java
>[INFO] 1 error

**Comment by aburkov** [comment]
Thank you!
