### ISSUE TITLE
Can you publish it to maven repo?

### ISSUE THREAD

**Issue by knirbhay** [WantedTechnologies/xpresso#2]

**Comment by sandeepan** [comment]
Same question :)

**Comment by sandeepan** [comment]
@knirbhay 

If you still want to run it locally. You can do the follow.
Download the jar from target folder of the repo and run the command below. It'll install the dependency in local .m2 directory.But to deploy it to remote machine, you'll have to repeat the process

mvn install:install-file -Dfile=xpresso-0.1.5.jar -DgroupId=wantedtechnologies -DartifactId=xpresso -Dversion=1.1 -Dpackaging=jar -DgeneratePom=true

and add the dependency to your local project

        <dependency>
            <groupId>wantedtechnologies</groupId>
            <artifactId>xpresso</artifactId>
            <version>1.1</version>
        </dependency>
You can choose to change the grouoID and artifactid.

Or you could take the pain and deploy it on maven central yourself after cloning the code locally. I took the shorter path :)

**Comment by NirbhayK** [comment]
I am doing the same as of now. But if you include it in local repo and try to build it on systems like travis you have ship the jar with the code. Ideally, it should be published by the Author itself. Let see if I can find a way.

**Comment by sandeepan** [comment]
Sounds Painful. We'll wait for the author to reply

**Comment by aburkov** [comment]
Hi! I'm working on this right now, I'll keep you updated.

**Comment by aburkov** [comment]
Here we go:

<dependency>
    <groupId>com.cebglobal</groupId>
    <artifactId>xpresso</artifactId>
    <version>0.9.0</version>
</dependency>

**Comment by knirbhay** [comment]
Thanks Aburkov
